apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  labels:
    app: "{{ .Values.pvc.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pvc.storage }}"  # Define storage size in values.yaml
  storageClassName: "{{ .Values.pvc.storageClassName }}"  # Set the storage class
