namespace: default
replicaCount: 5

image:
  repository: argoproj/rollouts-demo
  tag:  blue  #3.12.14-management-alpine #3.8-management-alpine  

containerPort:  80  # Replace with your container port

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  hostname: green.jojos.tech
  path: /
  pathType: Prefix
